### ISSUE TITLE
Initialize repository

### ISSUE THREAD

**Issue by strohel** [tonarino/rusty-yunet#1]
## Tasks
- [x] Define a license - compatible with https://github.com/ShiqiYu/libfacedetection/blob/master/LICENSE
- [ ] Extend readme, add badges etc
- [x] Set-up branch protection rules etc.
- [ ] Set-up dependabot for dependency updates?
- [ ] Fill cargo metadata and cargo publish? Perhaps not needed now, can be a git dependency

**Comment by BaaMeows** [comment]
Would it be possible to have a license defined?
(Unlicensed code is scary!)
I've noticed that Tonari often uses the MIT license - I'd be happy to make a PR to add one if you'd like?

**Comment by strohel** [comment]
> Would it be possible to have a license defined? (Unlicensed code is scary!)

Agreed!

> I've noticed that Tonari often uses the MIT license - I'd be happy to make a PR to add one if you'd like?

We're be happy with MIT, but I see that [`libfacedetection`](https://github.com/ShiqiYu/libfacedetection) whose source code we bundle is under the 3-clause BSD license.

Do you know to which extent are these licenses compatible? I guess we should at least include (also) the BSD license text (in addition to the the chosen license, e.g. MIT).

If it would simplify things, we could as well license this whole project under 3-clause BSD.

**Comment by BaaMeows** [comment]
> Do you know to which extent are these licenses compatible? I guess we should at least include (also) the BSD license text (in addition to the the chosen license, e.g. MIT).

They're quite similar licenses and should be completely compatible; as you guessed, you just have to include libfacedetection's license in your project. (And you already are!)
The license for libfacedetection is included at the top of most of its source files, so [rusty-yunet has a few copies](https://github.com/tonarino/rusty-yunet/blob/main/src/libfacedetection/facedetectcnn.cpp); technically, you're already meeting the conditions of libfacedetection's license and can simply add any compatible license you'd like.

> If it would simplify things, we could as well license this whole project under 3-clause BSD.

You absolutely could! I don't think it would be simpler, but having libfacedetection's license be shared with yours instead of being relegated to its source files could be nice?
 All you'd need to do is add another copyright notice below libfacedetection's, make a few annotations and minor changes to make it clear that the license is for rusty-yunet and who made what (without modifying anything that legally needs to be included verbatim), and then you're done!
For example, [Quill's license](https://github.com/slab/quill/blob/develop/LICENSE) is BSD-3 and has multiple copyright notices. (It's doing so for quite different reasons, though, I think?)

**Comment by strohel** [comment]
@BaaMeows we had a quick chat in the team - we'll go with the MIT license. If you want to speed thinks up, we'll be happily accept a PR. 🙏
